spring:
  jpa:
    properties:
      hibernate:
        dialect: io.roach.stock.util.CockroachDBDialect
  datasource:
    url: jdbc:postgresql://localhost:26257/stock?sslmode=disable
    username: root
    password:
    hikari:
      transaction-isolation: TRANSACTION_SERIALIZABLE
